# Generated by Django 6.0.3 on 2026-03-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_category_alter_task_deadline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='parent_task',
            new_name='task',
        ),
    ]
